# Default config
spring:
  application:
    name: employee-management-system
  # TODO: turn off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  # Database config
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management_local
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
